USE master;
GO
CREATE DATABASE db_olap
GO
ALTER DATABASE db_olap SET ONLINE
GO
USE [db_olap]
GO

/****** Object:  Table [dbo].[DIM_CUSTOMER]    Script Date: 28/12/2024 12:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_CUSTOMER](
	[ID_Customer] [int] IDENTITY(1,1) NOT NULL,
	[RUC] [char](11) NOT NULL,
	[Nro_identity] [int] NOT NULL,
	[Business_name] [varchar](100) NOT NULL,
	[City_Name] [varchar](50) NOT NULL,
	[State_Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID_Customer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_PRODUCT]    Script Date: 28/12/2024 12:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_PRODUCT](
	[ID_Product] [int] IDENTITY(1,1) NOT NULL,
	[No_Prod] [char](5) NOT NULL,
	[description] [varchar](100) NOT NULL,
	[UP] [numeric](8, 2) NOT NULL,
	[Stock] [int] NOT NULL,
 CONSTRAINT [PK_DIM_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[ID_Product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_SALESPERSON]    Script Date: 28/12/2024 12:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_SALESPERSON](
	[ID_Salesperson] [int] IDENTITY(1,1) NOT NULL,
	[Cod_sales] [int] NOT NULL,
	[Names] [nvarchar](50) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[Birthdate] [date] NOT NULL,
 CONSTRAINT [PK_DIM_SALESPERSON] PRIMARY KEY CLUSTERED 
(
	[ID_Salesperson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_TIME]    Script Date: 28/12/2024 12:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_TIME](
	[ID_Fecha] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NOT NULL,
	[Year] [nchar](10) NOT NULL,
	[Month] [nchar](10) NOT NULL,
	[Day] [nchar](10) NOT NULL,
	[Semester] [nchar](10) NOT NULL,
	[Trimester] [nchar](10) NOT NULL,
	[Name_Month] [nchar](10) NOT NULL,
	[Name_Day] [nchar](10) NOT NULL,
 CONSTRAINT [PK_DIM_TIME] PRIMARY KEY CLUSTERED 
(
	[ID_Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICE_SALES]    Script Date: 28/12/2024 12:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICE_SALES](
	[ID_Customer] [int] NOT NULL,
	[ID_Product] [int] NOT NULL,
	[ID_Salesperson] [int] NOT NULL,
	[ID_Fecha] [int] NOT NULL,
	[Quantity] [numeric](8, 2) NOT NULL,
	[UP] [numeric](8, 2) NOT NULL,
	[Descount] [numeric](3, 2) NOT NULL,
	[Total] [money] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICE_SALES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_SALES_DIM_CUSTOMER] FOREIGN KEY([ID_Customer])
REFERENCES [dbo].[DIM_CUSTOMER] ([ID_Customer])
GO
ALTER TABLE [dbo].[INVOICE_SALES] CHECK CONSTRAINT [FK_INVOICE_SALES_DIM_CUSTOMER]
GO
ALTER TABLE [dbo].[INVOICE_SALES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_SALES_DIM_PRODUCT] FOREIGN KEY([ID_Product])
REFERENCES [dbo].[DIM_PRODUCT] ([ID_Product])
GO
ALTER TABLE [dbo].[INVOICE_SALES] CHECK CONSTRAINT [FK_INVOICE_SALES_DIM_PRODUCT]
GO
ALTER TABLE [dbo].[INVOICE_SALES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_SALES_DIM_SALESPERSON] FOREIGN KEY([ID_Salesperson])
REFERENCES [dbo].[DIM_SALESPERSON] ([ID_Salesperson])
GO
ALTER TABLE [dbo].[INVOICE_SALES] CHECK CONSTRAINT [FK_INVOICE_SALES_DIM_SALESPERSON]
GO
ALTER TABLE [dbo].[INVOICE_SALES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICE_SALES_DIM_TIME] FOREIGN KEY([ID_Fecha])
REFERENCES [dbo].[DIM_TIME] ([ID_Fecha])
GO
ALTER TABLE [dbo].[INVOICE_SALES] CHECK CONSTRAINT [FK_INVOICE_SALES_DIM_TIME]
GO
