-- Queries for OLAP System
USE db_olap
GO
-- 1. Dimension Queries
-- List all customers from DIM_CUSTOMER
SELECT ID_Customer, RUC, Nro_identity, Business_name, City_Name, State_Name
FROM dbo.DIM_CUSTOMER;

-- List all products from DIM_PRODUCT
SELECT ID_Product, No_Prod, description, UP, Stock
FROM dbo.DIM_PRODUCT;

-- List all salespersons from DIM_SALESPERSON
SELECT ID_Salesperson, Cod_sales, Names, Gender, Birthdate
FROM dbo.DIM_SALESPERSON;

-- List all time entries from DIM_TIME
SELECT ID_Fecha, Date, Year, Month, Day, Semester, Trimester, Name_Month, Name_Day
FROM dbo.DIM_TIME;

-- 2. Fact Table Queries
-- List all sales records from INVOICE_SALES
SELECT ID_Customer, ID_Product, ID_Salesperson, ID_Fecha, Quantity, UP, Descount, Total
FROM dbo.INVOICE_SALES;

-- Total revenue generated by all invoices
SELECT SUM(Total) AS TotalRevenue
FROM dbo.INVOICE_SALES;

-- Total quantity sold for each product
SELECT p.ID_Product, p.description, SUM(f.Quantity) AS TotalQuantitySold
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_PRODUCT p ON f.ID_Product = p.ID_Product
GROUP BY p.ID_Product, p.description
ORDER BY TotalQuantitySold DESC;

-- Total revenue generated by each customer
SELECT c.ID_Customer, c.Business_name, SUM(f.Total) AS CustomerRevenue
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_CUSTOMER c ON f.ID_Customer = c.ID_Customer
GROUP BY c.ID_Customer, c.Business_name
ORDER BY CustomerRevenue DESC;

-- Total revenue generated by each salesperson
SELECT s.ID_Salesperson, s.Names, SUM(f.Total) AS SalespersonRevenue
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_SALESPERSON s ON f.ID_Salesperson = s.ID_Salesperson
GROUP BY s.ID_Salesperson, s.Names
ORDER BY SalespersonRevenue DESC;

-- 3. Advanced Analytics Queries
-- Monthly sales revenue
SELECT t.Year, t.Month, SUM(f.Total) AS MonthlyRevenue
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_TIME t ON f.ID_Fecha = t.ID_Fecha
GROUP BY t.Year, t.Month
ORDER BY t.Year, t.Month;

-- Top 5 products by revenue
SELECT TOP 5 p.ID_Product, p.description, SUM(f.Total) AS ProductRevenue
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_PRODUCT p ON f.ID_Product = p.ID_Product
GROUP BY p.ID_Product, p.description
ORDER BY ProductRevenue DESC;

-- Revenue breakdown by state
SELECT c.State_Name, SUM(f.Total) AS StateRevenue
FROM dbo.INVOICE_SALES f
INNER JOIN dbo.DIM_CUSTOMER c ON f.ID_Customer = c.ID_Customer
GROUP BY c.State_Name
ORDER BY StateRevenue DESC;
